### ISSUE TITLE
Incorrect reference?

### ISSUE THREAD

**Issue by firthmj** [AMWA-TV/nmos-authorization#111]
The "Public Keys" section of "Behaviour: Resource Servers" page (https://specs.amwa.tv/is-10/releases/v1.0.0/docs/4.5._Behaviour_-_Resource_Servers.html#public-keys) includes the following text:

"it SHOULD attempt to obtain the missing public key via the the token iss claim as specified in RFC 8414 section 3"

From what I can see, RFC8414 section 3 does not describe how to obtain public keys via the token iss claim. Initially I thought this was an error in INFO-002, but it seems the INFO-002 text is copied from IS-10.

Additionally, it seems some OAuth2 implementations/code includes a "kid" parameter in the JWT header to provide the public key ID that it has been signed with. Should some reference to that be included in this section?

**Comment by lo-simon** [comment]
The step on how to fetch the token issuer (`iss` is an URL of the Authorization server) public keys are done via the Authorization server's `public keys endpoint`, which is described in https://specs.amwa.tv/is-10/releases/v1.0.0/docs/4.1._Behaviour_-_Authorization_Servers.html#authorization-server-public-keys. In the spec we mention `RFC 8414 section 3` is because the `public keys endpoint` is specified inside the Authorization server's metadata. So therefore to obtain the server's public keys, we need to obtain the Authorization server's metadata first. The `Authorization server metadata endpoint` is constructed by the `iss`/.well-known/example-configuration.

The `kid` specified in the `JWT header` shows which key was used to encode it. The `kid` can be used to locate the matching key in the Authorization server's `jwks` for JWT validation.

**Comment by garethsb** [comment]
(When presented with a JWT, what is to prevent it having an `iss` identifying a rogue authorization server? An auth server can have a valid chain of trust confirming its identity, while still being inappropriate for the system in question, I would have thought... This is a separate issue though... Now added as https://github.com/AMWA-TV/is-10/issues/114.)

**Comment by garethsb** [comment]
> "it SHOULD attempt to obtain the missing public key via the the token iss claim as specified in RFC 8414 section 3"

Personally, my confusion was that this explanation skips over the step of fetching the JSON Web Key Set (JWKS) from the `jwks_uri` after having fetched the authorization server metadata for the issuer identified by the `iss` claim using the `.well-known` mechanism, which is the bit specified by RFC 8414 section 3. It doesn't help that "public key" and "JWKS" are not immediately obvious synonyms.

**Comment by peterbrightwell** [comment]
Looks like it will need correction or clarification
Architecture Review Group review: place on backlog

**Comment by jonathan-r-thorpe** [comment]
Fixed by #115
