### ISSUE TITLE
Schemas

### ISSUE THREAD

**Issue by lo-simon** [AMWA-TV/nmos-authorization#25]
1. auth_metadata.json
remove "jwks_uri", "revocation_endpoint", and "code_challenge_methods_supported" from required, as they are marked as optional according to the RFC8414 see https://tools.ietf.org/html/rfc8414#section-2

2. register_client_request.json & register_client_response.json
OpenID has added new response_types on top of oauh2.0 'code, token', they are 'id_token, id_token token, code id_token, code token, code id_token token, none'. Should they be added in the register_client_request & register_client_response schemas?  I think at least 'none' is needed to be added in the register_client_response.json as it is currently returning by the keycloak auth server after a successful client registration.
see https://openid.net/specs/oauth-v2-multiple-response-types-1_0.html
see interesting article https://medium.com/@darutk/diagrams-of-all-the-openid-connect-flows-6968e3990660

3. jwks_response.json
x5c should be an array of string rather than just a string, as shown in RFC7517
see https://tools.ietf.org/html/rfc7517#section-4.7

4. token_response.json
Not sure whether "Bearer" or "bearer" should be used for token_type, the keycloak auth server is using "bearer"?  We can have both "Bearer" and "bearer" in the schema, and how about "BEARER"?
see https://tools.ietf.org/html/rfc6749#section-7.1

**Comment by dannymeloy** [comment]
Hi Simon,  thanks for your comments.

1. The code_challenge_methods metadata field is required as the absence of the claim implies that PKCE is not supported: "If omitted, the authorization server does not support PKCE" (https://tools.ietf.org/html/rfc8414). Equally with the jwks_uri, if we are choosing to validate tokens based on JSON Web Keys then this will need to be defined in the metadata if it is going to be discovered dynamically.
2. To date we haven't really looked at OpenID Connect, due to it being used mostly as an identification protocol. We could certainly add "none", and any other OIDC response_types if we think that would be beneficial in using OTS auth servers.
3. This is valid, please feel free to put in a PR to make the relevant change.
4. The token should likely always be "Bearer" as given in https://tools.ietf.org/html/rfc6750. But I think allowing a case-insensitive match on the Resource Server side would be beneficial to ease interoperability.

**Comment by lo-simon** [comment]
1. yes I agreed, how about just removing the revocation_endpoint, as it is not a requiement for NMOS. And especially keycloak auth server does not retruning this information for the auth metadata.

**Comment by lo-simon** [comment]
back to no. 1,  some auth server may not be supporting PKCE, then the code_challenge_methods would be omitted from the response of the auth metadata, so adding PKCE or not while requesting authorization code should be down to the developer based on the present of 'code_challenge_methods'.  Therefore I don't think 'code_challenge_methods' should the required element in the auth_metadata schema.

**Comment by dannymeloy** [comment]
Hi Simon, I agree that the "revocation_endpoint" field should be removed from being "required". Keycloak is a widely used authorization solution and it appears to handle revocation in an internal way. Perhaps altering it to "IF the revocation endpoint is present in the metadata then it MUST be used to revoke tokens ... etc etc"

With regards to the "code_challenge_methods" endpoint, due to PKCE now being recommended in the OAuth Best Common Practices, (https://tools.ietf.org/html/draft-ietf-oauth-security-topics-15#section-2.1.1) and it being supported by the majority of Auth Solutions (including Keycloak), I'd argue that we should not be supporting OTS Solutions that do not support PKCE, making this requirement valid.

**Comment by NEOAdvancedTechnology** [comment]
Item #1 - PR in the works

Item #2,3,4 - Solved with merged PRs
